### ISSUE TITLE
How to assign 4 fingers tap to a fusuma-sendkey command?

### ISSUE THREAD

**Issue by pedrofleck** [iberianpig/fusuma-plugin-tap#12]
I tried following the instructions but I couldn't get it to work, I need the "fusuma-sendkey" because I'm running Wayland.

**Comment by iberianpig** [comment]
Unfortunately, if you are using libinput v1.17.0 or later, fusuma-plugin-tap will not work.
see https://github.com/iberianpig/fusuma-plugin-tap/issues/13#issuecomment-803597089

**Comment by pedrofleck** [comment]
That's unfortunate. But thanks for the answer!

**Comment by pedrofleck** [comment]
@iberianpig ok, thank you!
