### ISSUE TITLE
tap 4 not registered

### ISSUE THREAD

**Issue by gasdia73** [iberianpig/fusuma-plugin-tap#4]
On my kubuntu 20.04 machine lenovo c940 I cannot make the tap 4 gesture work.
while the message is correctly displayed in the console for tap 3 gesture, it doesn't happen for tap 4.
this is my config.yml

[config.txt](https://github.com/iberianpig/fusuma-plugin-tap/files/4639655/config.txt)

**Comment by iberianpig** [comment]
Could you paste outputs of `fusuma --version`?

**Comment by gasdia73** [comment]
sure

I, [2020-05-17T12:17:13.843506 #3151]  INFO -- : ---------------------------------------------
I, [2020-05-17T12:17:13.843539 #3151]  INFO -- : Fusuma: 1.10.1
I, [2020-05-17T12:17:13.844813 #3151]  INFO -- : libinput: 1.15.5
I, [2020-05-17T12:17:13.845426 #3151]  INFO -- : OS: Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020
I, [2020-05-17T12:17:13.845785 #3151]  INFO -- : Distribution: Ubuntu 20.04 LTS \n \l
I, [2020-05-17T12:17:13.846085 #3151]  INFO -- : Desktop session: plasma x11
I, [2020-05-17T12:17:13.846107 #3151]  INFO -- : ---------------------------------------------
I, [2020-05-17T12:17:13.846114 #3151]  INFO -- : Enabled Plugins: 
I, [2020-05-17T12:17:13.846286 #3151]  INFO -- :   Fusuma::Plugin::Buffers::GestureBuffer
I, [2020-05-17T12:17:13.846293 #3151]  INFO -- :   Fusuma::Plugin::Buffers::KeypressBuffer
I, [2020-05-17T12:17:13.846297 #3151]  INFO -- :   Fusuma::Plugin::Detectors::KeypressDetector
I, [2020-05-17T12:17:13.846341 #3151]  INFO -- :   Fusuma::Plugin::Detectors::PinchDetector
I, [2020-05-17T12:17:13.846374 #3151]  INFO -- :   Fusuma::Plugin::Detectors::RotateDetector
I, [2020-05-17T12:17:13.846380 #3151]  INFO -- :   Fusuma::Plugin::Detectors::SwipeDetector
I, [2020-05-17T12:17:13.846385 #3151]  INFO -- :   Fusuma::Plugin::Events::Records::GestureRecord
I, [2020-05-17T12:17:13.846389 #3151]  INFO -- :   Fusuma::Plugin::Events::Records::IndexRecord
I, [2020-05-17T12:17:13.846394 #3151]  INFO -- :   Fusuma::Plugin::Events::Records::KeypressRecord
I, [2020-05-17T12:17:13.846434 #3151]  INFO -- :   Fusuma::Plugin::Events::Records::TextRecord
I, [2020-05-17T12:17:13.846439 #3151]  INFO -- :   Fusuma::Plugin::Executors::CommandExecutor
I, [2020-05-17T12:17:13.846445 #3151]  INFO -- :   Fusuma::Plugin::Executors::WmctrlExecutor
I, [2020-05-17T12:17:13.846450 #3151]  INFO -- :   Fusuma::Plugin::Filters::KeypressFilter
I, [2020-05-17T12:17:13.846455 #3151]  INFO -- :   Fusuma::Plugin::Filters::LibinputDeviceFilter
I, [2020-05-17T12:17:13.846460 #3151]  INFO -- :   Fusuma::Plugin::Filters::LibinputTimeoutFilter
I, [2020-05-17T12:17:13.846465 #3151]  INFO -- :   Fusuma::Plugin::Inputs::LibinputCommandInput
I, [2020-05-17T12:17:13.846471 #3151]  INFO -- :   Fusuma::Plugin::Parsers::KeypressParser
I, [2020-05-17T12:17:13.846476 #3151]  INFO -- :   Fusuma::Plugin::Parsers::LibinputGestureParser
I, [2020-05-17T12:17:13.846481 #3151]  INFO -- : ---------------------------------------------

**Comment by iberianpig** [comment]
Sorry for your reply.
I checked my environment but it works well.


Are you using fusuma-plugin-tap 0.3.1?
```shell
$ gem list | grep fusuma
fusuma (1.10.1)
fusuma-plugin-keypress (0.1.1)
fusuma-plugin-sendkey (0.4.0, 0.1.1)
fusuma-plugin-tap (0.3.1)
fusuma-plugin-wmctrl (0.3.0)
```

**Comment by gasdia73** [comment]
from your last suggestion I realized that I didn't have the plugin installed.
Sorry about that, I'm closing the issue.
